#Lab8 - Python List lab
print("*----------------------------------------------*")
print(" Lab8 List Assignment by Wook Huang ")
print("*----------------------------------------------*")
print('')
print("1. Create a list, assign 5 different values and display it using the print command")
list_of_courses =['Orientation','Software Quality','DB system','SQL','Cloud infra','Test Automation']
print('')
print(list_of_courses)
print('')
print("*----------------------------------------------*")
print('')
print("2. Add a new value to the end of the list and display it using the print command")
Course_Lists=list(list_of_courses)
print('Add Python to the list')
Course_Lists.append('Python')
print(Course_Lists)
print('')
print("*----------------------------------------------*")
print('')
print("3. Remove the second value from the list and display it using the print command")
Course_Lists.pop(1)
print(Course_Lists)
print('')
print("*----------------------------------------------*")
print('')
print("4. Check the length of the list and display it using the print command")
print('length of current list :', len(Course_Lists))
print('')
print("*----------------------------------------------*")
print('')
print("5. Display the first item using the print command")
print(Course_Lists[0])
print('')
print("*----------------------------------------------*")
print("* 6. Display the last item using the print command")
#print(Course_Lists[len(Course_Lists)-1])
print(Course_Lists[-1])

print("*----------------------------------------------*")
